=== visual-decaf/decaf-compiler/json/ast/ArithmeticBinary_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Visual Decaf ArithmeticBinary Schema",
    "type": "object",
    "properties": {
        "type": {
            "type": "string",
            "enum": [
                "ArithmeticBinary"
            ]
        },
        "operation": {
            "type": "string",
            "enum": [
                "PLUS",
                "MINUS",
                "MULTIPLY",
                "DIVIDE"
            ]
        },
        "left": {
            "oneOf": [
                {
                    "$ref": "#"
                },
                {
                    "$ref": "./IntConstant_schema.json"
                }
            ]
        },
        "right": {
            "oneOf": [
                {
                    "$ref": "#"
                },
                {
                    "$ref": "./IntConstant_schema.json"
                }
            ]
        }
    },
    "required": [
        "type",
        "operation",
        "left",
        "right"
    ]
}

=== visual-decaf/decaf-compiler/json/ast/Expr.json
{
    "type": "ArithmeticBinary",
    "operation": "DIVIDE",
    "left": {
        "type": "ArithmeticBinary",
        "operation": "MULTIPLY",
        "left": {
            "type": "IntConstant",
            "value": 1
        },
        "right": {
            "type": "IntConstant",
            "value": 2
        }
    },
    "right": {
        "type": "IntConstant",
        "value": 3
    }
}
